- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
        force_apt_get: true
      tags:
       - node
       - zsh
  tasks:
    - include: tasks/nvim-setup.yml
    - include: tasks/productivity-tools.yml 
    - include: tasks/zsh-setup.yml
    - include: tasks/git-setup.yml
