- name: Install System Packages 1 (cmake, pkg-config)
  homebrew:
    name: ["cmake", "pkg-config"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, gettext)
  homebrew:
    name: [ "lua", "unzip", "libtool", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  homebrew:
    name: ["curl", "htop", "golang", "lsof", "ccache", "ninja"]
  tags:
    - install
    - core
