- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "brandonfidler57@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Brandon Fidler"
  tags:
  - git-personal
    - name: Git work email setup
  git_config:
    name: user.email
    scope: global
    value: "brandonfidler@outlook.com"
  tags:
  - git-work
- name: Git work setup name
  git_config:
    name: user.name
    scope: global
    value: "Brandon Fidler"
  tags:
  - git-work
